config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  devise_for :users
 
  resources :posts, shallow: true do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#destroy'
    resources :comments, only: [:new, :create]
  end
 
  resources :circles, only: [:index, :new, :create, :show]

  resources :topics do
    resources :topiccomments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'イタリアン' },
    { id: 3, name: 'フレンチ' },
    { id: 4, name: '和食' },
    { id: 5, name: '洋食' },
    { id: 6, name: '中華' },
    { id: 7, name: 'エスニック' },
    { id: 8, name: '韓国料理' },
    { id: 9, name: 'スイーツ' },
    { id: 10, name: 'デザート' },
    { id: 11, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts
  has_many :circles
  has_many :topics
end

app/models/circle.rb
class Circle < ApplicationRecord
  has_many :users, through: :circle_users
  has_many :topics
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :explanation
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :keyword_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :keyword

  
end

app/models/circle_user.rb
class CircleUser < ApplicationRecord
  belongs_to :circle
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/keyword.rb
class Keyword < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'お弁当' },
    { id: 3, name: 'おもてなし' },
    { id: 4, name: 'おつまみ' },
    { id: 5, name: '時短' },
    { id: 6, name: 'おしゃれ' },
    { id: 7, name: 'パーティ' },
    { id: 8, name: 'まかない' },
    { id: 9, name: 'イベント' }
  ]

  include ActiveHash::Associations
  has_many :posts
  has_many :circles
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :explanation
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :keyword_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :keyword
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :topiccomments

  with_options presence: true do
    validates :name
    validates :text
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
  end
end

app/models/topiccomment.rb
class Topiccomment < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates :text, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :facorites
  has_many :fav_posts, through: :favorites, source: :post
  has_many :comments
  has_many :circles, through: :circle_users
  has_many :topics

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }
  validates_format_of :password, with: /([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])/, length: { minimum: 6 }, message: 'は6文字以上の英数混在で入力してください。'
  validates :birthday, presence: true

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'に全角文字を使用してください' } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: 'に全角文字を使用してください' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  def like(post)
    favorites.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    favorite = favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @posts = Post.order(id: :DESC)
    @circles = Circle.order(id: :DESC)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :post_find, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order(id: :DESC)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to root_path if current_user.id != @post.user.id or @post.order != nil
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @post.user.id
      @post.destroy
    end
      redirect_to root_path
  end

  private

  def post_find
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :category_id, :keyword_id, :explanation, :recipe, :image).merge(user_id: current_user.id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topiccomments_helper.rb
module TopiccommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/homes/index.html.erb
   <!-- Page Content -->
  <div class="container">

    <div class="row">

          <div class="col-lg-3">
            <h1 class="my-4">　</h1>
              <div class="list-group">
                <% if @circles[0] != nil %>
                  <% @circles.each do |circle| %>
                    <%= link_to circle.name, circle_path(circle), class: "list-group-item" %>
                  <% end %>
                <% end %>
              <%= link_to "create new circle", new_circle_path, class: "list-group-item-create" %>
            </div>
          </div>

      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <%= image_tag 'topview.jpg' , size: '900x300' ,class: "d-block img-fluid" %>
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      <%# 商品がない場合のダミー画像表示 %>
      <% if @posts.length == 0 %>
        <li class='list'>
          <%= link_to '#' do %>
            <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
            <div class='item-info'>
              <h3 class='item-name'>
                投稿してみよう！
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>

<%= link_to(new_post_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>


      <div class="row">

          <% if @posts[0] != nil %>
            <% @posts.each do |post| %>
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card h-100">
                    <%= link_to post_path(post) do %>
                      <%= image_tag post.image, class: "card-img-top" %>
                      <div class="card-body">
                        <h4 class="card-title">
                          <%= post.name %></h4>
                          <span class="badge rounded-pill bg-light text-dark my-2"><%= post.category.name %></span>
                        <%# <p class="card-text"><%= post.explanation %>
                      </div>
                      <div class="card-footer">
                      </div>
                    <% end %>
                  </div>
                </div>
            <% end %>
          <% end %>



        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->


</body>

</html>