config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  devise_for :users
 
  resources :posts, shallow: true do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#destroy'
    resources :comments, only: [:new, :create]
  end
 
  resources :circles, only: [:index, :new, :create, :show]

  resources :topics do
    resources :topiccomments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'イタリアン' },
    { id: 3, name: 'フレンチ' },
    { id: 4, name: '和食' },
    { id: 5, name: '洋食' },
    { id: 6, name: '中華' },
    { id: 7, name: 'エスニック' },
    { id: 8, name: '韓国料理' },
    { id: 9, name: 'スイーツ' },
    { id: 10, name: 'デザート' },
    { id: 11, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts
  has_many :circles
  has_many :topics
end

app/models/circle.rb
class Circle < ApplicationRecord
  has_many :users, through: :circle_users
  has_many :topics
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :explanation
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :keyword_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :keyword

  
end

app/models/circle_user.rb
class CircleUser < ApplicationRecord
  belongs_to :circle
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/keyword.rb
class Keyword < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'お弁当' },
    { id: 3, name: 'おもてなし' },
    { id: 4, name: 'おつまみ' },
    { id: 5, name: '時短' },
    { id: 6, name: 'おしゃれ' },
    { id: 7, name: 'パーティ' },
    { id: 8, name: 'まかない' },
    { id: 9, name: 'イベント' }
  ]

  include ActiveHash::Associations
  has_many :posts
  has_many :circles
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :explanation
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :keyword_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :keyword
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :topiccomments

  with_options presence: true do
    validates :name
    validates :text
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
  end
end

app/models/topiccomment.rb
class Topiccomment < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates :text, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :facorites
  has_many :fav_posts, through: :favorites, source: :post
  has_many :comments
  has_many :circles, through: :circle_users
  has_many :topics

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }
  validates_format_of :password, with: /([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])/, length: { minimum: 6 }, message: 'は6文字以上の英数混在で入力してください。'
  validates :birthday, presence: true

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'に全角文字を使用してください' } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: 'に全角文字を使用してください' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  def like(post)
    favorites.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    favorite = favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @posts = Post.order(id: :DESC)
    @circles = Circle.order(id: :DESC)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :post_find, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order(id: :DESC)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to root_path if current_user.id != @post.user.id or @post.order != nil
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @post.user.id
      @post.destroy
    end
      redirect_to root_path
  end

  private

  def post_find
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :category_id, :keyword_id, :explanation, :recipe, :image).merge(user_id: current_user.id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:edit, :show]
  
  def index
    @topics = Topic.order[id: :DESC]
  end
  
  def create
    @topic = Topic.create(topic_params)
    if @topic.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def edit
  end


  private

  def topic_params
    params.require(:topic).permit(:name, :image, :text, :category_id).merge(user_id: current_user.id)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topiccomments_helper.rb
module TopiccommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/posts/edit.html.erb
<div class="items-sell-contents">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">新規投稿</h2>
    <%= form_with model: @post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
   
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"投稿の説明" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
        <div class="weight-bold-text">
          キーワード
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:keyword_id, Keyword.all, :id, :name, {}, {class:"select-box", id:"post-keyword"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>


    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="items-sell-contents">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">新規投稿</h2>
    <%= form_with model: @post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
   
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"投稿の説明" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          レシピ
        </div>
        <%= f.text_area :recipe, class:"items-text", id:"item-info", placeholder:"recipe" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
        <div class="weight-bold-text">
          キーワード
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:keyword_id, Keyword.all, :id, :name, {}, {class:"select-box", id:"post-keyword"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>


    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/posts/show.html.erb
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @post.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @post.image ,class:"item-box-img" %>  
    </div>
    

    <% if user_signed_in? %>
      <% if current_user == @post.user %> 
        <%= link_to '投稿の編集', edit_post_path, method: :get, class: "item-red-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削除', post_path(@post.id), method: :delete, class:'item-destroy' %>
     <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= simple_format(@post.explanation) %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @post.user.nickname %></td>
          </tr>
          <tr>
          <th class="detail-item">recipe</th>
          <td class="detail-value"><%= simple_format(@post.recipe) %></td>
        </tr>
  
      </tbody>
    </table>
    
    <% if user_signed_in? %>
    <div class="option">
      <div class="favorite-btn">
        <% if !Favorite.exists?(user_id:current_user.id,post_id:@post.id) %>
    <%= link_to "お気に入り",post_add_path(@post),method: :post %>
    <% else %>
    <%= link_to "お気に入り解除",post_add_path(@post),method: :delete %>
    <% end %>
    </div>
  </div>
  <% end %>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の投稿
    </a>
    <a href="#" class="change-item-btn">
      後ろの投稿 ＞
    </a>
  </div>
  <%# <a href="#" class='another-item'><%= @post.category.name %>
  <%# をもっと見る</a> %>
</div>

app/views/topics/new.html.erb
<div class="items-sell-contents">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">新規投稿</h2>
    <%= form_with model: @topic, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
   
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="optional">任意</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
       <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          メッセージ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"message" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>